name: Continuous Deployment

on:
  push:
    branches:
      - develop

env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  Build-Android-Dev-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install node modules
        run: |
          yarn

      - name: Create signing settings
        run: |
          echo keyPassword=\${{ secrets.DEV_KEYSTORE_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.DEV_KEYSTORE_STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.DEV_KEYSTORE_ALIAS }} >> ${{env.PROPERTIES_PATH}}

      - name: Create signing file
        run: |
          echo "${{ secrets.DEV_KEYSTORE }}" | base64 --decode > android/app/key.jks

      - name: Make gradlew executable
        run: |
          cd android && chmod +x ./gradlew
        
      - name: Build development variant
        run: |
          cd android && ./gradlew app:assembleDevelopment --no-daemon

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: davi.santos/Cripto-Dave-App
          token: ${{secrets.APPCENTER_TOKEN_ANDROID}}
          group: Collaborators
          file: app/build/outputs/apk/development/app-development.apk
          notifyTesters: true
          debug: false
